# Generated by Django 3.1.7 on 2021-03-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('logo', models.URLField(verbose_name='Logotipo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('product_type', models.SmallIntegerField(choices=[(1, 'Camisa'), (2, 'Camiseta'), (3, 'Polo'), (4, 'Calça'), (5, 'Bermuda'), (6, 'Casaco')], verbose_name='Tipo')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], verbose_name='Gênero')),
                ('size', models.SmallIntegerField(choices=[(1, 'PP'), (2, 'P'), (3, 'M'), (4, 'G'), (5, 'GG')], verbose_name='Tamanho')),
                ('color', models.CharField(max_length=50, verbose_name='Cor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
            ],
        ),
    ]
