# Generated by Django 3.1.7 on 2021-03-27 03:59

from django.db import migrations

def create_data(apps, schema_editor):
    ProductCategory = apps.get_model('products', 'ProductCategory')
    prod_category = ProductCategory(name="Moda praia", description="Últimas tendências para o verão na praia.").save()

    Brand = apps.get_model('products', 'Brand')
    brand = Brand(name="Oakley", logo="https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/072016/untitled-1_279.png").save()

    Product = apps.get_model('products', 'Product')
    Product(name="Camiseta Praia Branca", category=prod_category, product_type=2, gender=1, size=3, brand=brand, color="Branca", price=54.98).save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        (migrations.RunPython(create_data))
    ]
