# Generated by Django 3.1.7 on 2021-03-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(default='https://lh3.googleusercontent.com/proxy/tmW80bYKouP4BO3pUPYoCIVcW0rjJopBnkgPk_Vfi9SH6FVdQjqfOeG0TPOzXWuqlKUij9ICnlWiwSKOnpMIoTklBw', verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
    ]
